import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import CustomBigCalendar from '../components/CustomBigCalendar';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>UI Test with React Big Calendar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <h1>UI Test with React Big Calendar</h1>
          <CustomBigCalendar />
        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
